import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { Project, Task, ProjectType, WebDevelopmentDetails, ProjectFile, User, TaskStatus, UserRole } from '../../types';
import { PROJECT_STATUSES, PROJECT_TYPES, BLANK_PROJECT } from '../../constants';
import * as fileStorage from '../../utils/fileStorage';
import TaskList from './TaskList';
import ProjectTimeline from './ProjectTimeline';
import { FileIcon } from '../icons/FileIcon';
import { TrashIcon } from '../icons/TrashIcon';
import { UploadIcon } from '../icons/UploadIcon';
import PaginationControls from '../PaginationControls';
import { useStore } from '../../store/store';
import { ProjectModalTab } from '../../types';
import BaseModal from '../shared/BaseModal';
import { XIcon } from '../icons/XIcon';

interface ProjectModalProps {
  project: Project | null;
  isCreating: boolean;
  initialTab?: ProjectModalTab;
  onClose: () => void;
}

const DevStageCheckbox: React.FC<{
    label: string;
    isChecked: boolean;
    onChange: () => void;
    disabled: boolean;
}> = ({ label, isChecked, onChange, disabled }) => (
    <label className={`flex items-center gap-2 p-3 bg-[#2C3E5F] rounded-md transition-colors ${disabled ? 'cursor-not-allowed opacity-60' : 'cursor-pointer hover:bg-[#2C3E5F]/50'}`}>
        <input
            type="checkbox"
            checked={isChecked}
            onChange={onChange}
            disabled={disabled}
            className="w-4 h-4 text-[#00B7C1] bg-slate-600 border-slate-500 rounded focus:ring-[#00B7C1] focus:ring-2"
        />
        <span className="text-sm font-medium text-slate-200">{label}</span>
    </label>
);


const ProjectModal: React.FC<ProjectModalProps> = ({ project, isCreating, initialTab = 'details', onClose }) => {
  const { 
    allTasks, 
    users, 
    currentUser, 
    permissions, 
    saveProject, 
    addTask, 
    updateTask,
    openConfirmationModal,
    isSubmitting,
  } = useStore(state => ({
    allTasks: state.tasks,
    users: state.users,
    currentUser: state.currentUser!,
    permissions: state.permissions!,
    saveProject: state.saveProject,
    addTask: state.addTask,
    updateTask: state.updateTask,
    openConfirmationModal: state.openConfirmationModal,
    isSubmitting: state.isSubmitting,
  }));
  
  const tasks = useMemo(() => isCreating ? [] : allTasks.filter(t => t.projectId === project!.id), [allTasks, project, isCreating]);
  const projectManagers = useMemo(() => users.filter(u => u.role === UserRole.ProjectManager || u.role === UserRole.Admin), [users]);

  const [formData, setFormData] = useState<Project>(project || { ...BLANK_PROJECT, id: '', dealId: '' } as Project);
  const [initialData, setInitialData] = useState<Project | null>(null);
  const [activeTab, setActiveTab] = useState<ProjectModalTab>(isCreating ? 'details' : initialTab);
  const [projectFiles, setProjectFiles] = useState<ProjectFile[]>([]);
  const [isDragging, setIsDragging] = useState(false);
  const [taskCurrentPage, setTaskCurrentPage] = useState(1);
  const [taskItemsPerPage, setTaskItemsPerPage] = useState(5);
  
  const canEditProject = useMemo(() => {
    if (isCreating) return permissions.projects.create;
    if (!project || !permissions.projects.update) return false;
    if (currentUser.role === UserRole.Admin) return true;
    if (project.projectManagerId === currentUser.id) return true;
    if (currentUser.role === UserRole.Manager) {
        const pm = users.find(u => u.id === project.projectManagerId);
        if (pm && pm.groupId === currentUser.groupId) {
            return true;
        }
    }
    return false;
  }, [project, isCreating, currentUser, users, permissions]);

  useEffect(() => {
    if (isCreating) {
      const blankProject: Project = {
        ...BLANK_PROJECT,
        id: '', // Will be generated by API
        dealId: '', // Standalone project
        scope: currentUser.scope,
        projectManagerId: (currentUser.role === UserRole.ProjectManager || currentUser.role === UserRole.Admin) ? currentUser.id : null,
      };
      setFormData(blankProject);
      setInitialData(blankProject);
      setProjectFiles([]);
    } else if (project) {
        const initialDataObject = {
            ...BLANK_PROJECT,
            ...project,
            developmentDetails: project.developmentDetails || BLANK_PROJECT.developmentDetails,
            marketingDetails: project.marketingDetails || BLANK_PROJECT.marketingDetails
        };
        setFormData(initialDataObject);
        setInitialData(initialDataObject);
        setProjectFiles(fileStorage.getFilesForProject(project.id));
    }
    setActiveTab(isCreating ? 'details' : initialTab);
  }, [project, isCreating, initialTab, currentUser]);
  
  const parentTasks = useMemo(() => tasks.filter(t => !t.parentId), [tasks]);
  
  const totalTaskPages = Math.ceil(parentTasks.length / taskItemsPerPage);
  
  const paginatedParentTasks = useMemo(() => {
    const startIndex = (taskCurrentPage - 1) * taskItemsPerPage;
    return parentTasks.slice(startIndex, startIndex + taskItemsPerPage);
  }, [parentTasks, taskCurrentPage, taskItemsPerPage]);

  const hasUnsavedChanges = useMemo(() => {
    if (!initialData) return false;
    return JSON.stringify(formData) !== JSON.stringify(initialData);
  }, [formData, initialData]);

  const handleClose = useCallback(() => {
    if (activeTab === 'details' && hasUnsavedChanges && canEditProject) {
        openConfirmationModal(
            "تجاهل التغييرات؟",
            <p>لديك تغييرات غير محفوظة. هل أنت متأكد من رغبتك في الإغلاق؟<br />سيتم فقدان جميع التغييرات التي أجريتها.</p>,
            onClose
        );
    } else {
        onClose();
    }
  }, [activeTab, hasUnsavedChanges, canEditProject, onClose, openConfirmationModal]);
  
  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;

    if (name.startsWith('marketingDetails.')) {
        const field = name.split('.')[1];
        setFormData(prev => ({
            ...prev,
            marketingDetails: {
                ...prev.marketingDetails!,
                [field]: (e.target as HTMLInputElement).type === 'number' ? Number(value) : value,
            }
        }));
    } else if (name === 'projectType') {
        setFormData(prev => ({ ...prev, projectType: value as ProjectType }));
    } else if (name === 'services') {
        setFormData(prev => ({ ...prev, services: value.split('\n') }));
    } else {
        setFormData(prev => ({ ...prev, [name]: value }));
    }
  };

  const handleDevStageChange = (stage: keyof WebDevelopmentDetails['stages']) => {
    setFormData(prev => ({
        ...prev,
        developmentDetails: {
            ...prev.developmentDetails!,
            stages: {
                ...prev.developmentDetails!.stages,
                [stage]: !prev.developmentDetails!.stages[stage]
            }
        }
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!canEditProject) return;
    await saveProject(formData, isCreating);
    onClose();
  };
  
  const processFiles = useCallback((files: FileList) => {
    if (!files || files.length === 0 || !canEditProject || isCreating) return;
    
    Array.from(files).forEach(file => {
      const reader = new FileReader();
      reader.onload = (e) => {
        const fileData: ProjectFile = {
          name: file.name,
          size: file.size,
          type: file.type,
          content: e.target?.result as string,
        };
        fileStorage.saveFileForProject(project!.id, fileData);
        setProjectFiles(prev => [...prev, fileData]);
      };
      reader.readAsDataURL(file);
    });
  }, [project, canEditProject, isCreating]);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    processFiles(e.target.files!);
  };
  
  const handleFileDelete = (fileName: string) => {
    if (!canEditProject || isCreating) return;
    fileStorage.deleteFileForProject(project!.id, fileName);
    setProjectFiles(prev => prev.filter(f => f.name !== fileName));
  };
  
  // Drag and Drop handlers
  const handleDragOver = (e: React.DragEvent<HTMLDivElement>) => { e.preventDefault(); };
  const handleDragEnter = (e: React.DragEvent<HTMLDivElement>) => { e.preventDefault(); setIsDragging(true); };
  const handleDragLeave = (e: React.DragEvent<HTMLDivElement>) => { e.preventDefault(); setIsDragging(false); };
  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);
    processFiles(e.dataTransfer.files);
  };
  
  const formatFileSize = (bytes: number): string => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  }
  
  const completedTasks = tasks.filter(t => t.status === TaskStatus.DONE).length;
  const totalTasks = tasks.length;
  const progress = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;

  const renderTabContent = () => {
    switch(activeTab) {
      case 'details':
        return (
          <form id="project-form" onSubmit={handleSubmit} className="space-y-6">
              <fieldset disabled={!canEditProject || isSubmitting}>
                  {/* General Project Details */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4">
                      <div>
                          <label htmlFor="name" className="block text-sm font-medium text-slate-300 mb-1">اسم المشروع</label>
                          <input type="text" id="name" name="name" value={formData.name} onChange={handleChange} className="w-full bg-[#2C3E5F] border border-[#3E527B] rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#00B7C1] disabled:bg-[#2C3E5F]/50" required />
                      </div>
                      <div>
                          <label htmlFor="clientName" className="block text-sm font-medium text-slate-300 mb-1">اسم العميل</label>
                          <input type="text" id="clientName" name="clientName" value={formData.clientName} onChange={handleChange} className="w-full bg-[#2C3E5F] border border-[#3E527B] rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#00B7C1] disabled:bg-[#2C3E5F]/50" required />
                      </div>
                       <div className="md:col-span-2">
                          <label htmlFor="description" className="block text-sm font-medium text-slate-300 mb-1">وصف المشروع</label>
                          <textarea
                              id="description"
                              name="description"
                              value={formData.description || ''}
                              onChange={handleChange}
                              rows={3}
                              className="w-full bg-[#2C3E5F] border border-[#3E527B] rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#00B7C1] disabled:bg-[#2C3E5F]/50"
                              placeholder="أهداف المشروع، النطاق، وأي تفاصيل مهمة أخرى..."
                          ></textarea>
                      </div>
                      <div className="md:col-span-2">
                          <label htmlFor="services" className="block text-sm font-medium text-slate-300 mb-1">الخدمات المقدمة (كل خدمة في سطر)</label>
                          <textarea
                              id="services"
                              name="services"
                              value={formData.services.join('\n')}
                              onChange={handleChange}
                              rows={4}
                              className="w-full bg-[#2C3E5F] border border-[#3E527B] rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#00B7C1] disabled:bg-[#2C3E5F]/50"
                              placeholder="مثال:&#10;تصميم شعار&#10;إدارة حسابات التواصل الاجتماعي"
                          ></textarea>
                      </div>
                      <div>
                          <label htmlFor="startDate" className="block text-sm font-medium text-slate-300 mb-1">تاريخ البدء</label>
                          <input type="date" id="startDate" name="startDate" value={formData.startDate} onChange={handleChange} className="w-full bg-[#2C3E5F] border border-[#3E527B] rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#00B7C1] disabled:bg-[#2C3E5F]/50" />
                      </div>
                      <div>
                        <label htmlFor="projectManagerId" className="block text-sm font-medium text-slate-300 mb-1">مدير المشروع</label>
                        <select id="projectManagerId" name="projectManagerId" value={formData.projectManagerId || ''} onChange={handleChange} className="w-full bg-[#2C3E5F] border border-[#3E527B] rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#00B7C1] disabled:bg-[#2C3E5F]/50" required>
                            <option value="" disabled>اختر مدير مشروع</option>
                            {projectManagers.map(pm => (
                                <option key={pm.id} value={pm.id}>{pm.name}</option>
                            ))}
                        </select>
                      </div>
                      <div>
                          <label htmlFor="status" className="block text-sm font-medium text-slate-300 mb-1">الحالة</label>
                          <select id="status" name="status" value={formData.status} onChange={handleChange} className="w-full bg-[#2C3E5F] border border-[#3E527B] rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#00B7C1] disabled:bg-[#2C3E5F]/50">
                              {PROJECT_STATUSES.map(s => <option key={s.id} value={s.id}>{s.title}</option>)}
                          </select>
                      </div>
                  </div>

                  {/* Project Type Specific Details */}
                  <div className="border-t border-[#2C3E5F] pt-6 mt-6">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4">
                          <div className="md:col-span-2">
                              <label htmlFor="projectType" className="block text-sm font-medium text-slate-300 mb-1">نوع المشروع</label>
                              <select id="projectType" name="projectType" value={formData.projectType} onChange={handleChange} className="w-full bg-[#2C3E5F] border border-[#3E527B] rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#00B7C1] disabled:bg-[#2C3E5F]/50">
                                  {PROJECT_TYPES.map(s => <option key={s.id} value={s.id}>{s.title}</option>)}
                              </select>
                          </div>

                          {/* Web Development Fields */}
                          {formData.projectType === ProjectType.WEB_DEVELOPMENT && (
                              <div className="md:col-span-2 space-y-3">
                                  <h3 className="text-base font-semibold text-slate-200 border-b border-[#3E527B] pb-2">مراحل التطوير</h3>
                                  <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                                      <DevStageCheckbox label="تحليل" isChecked={formData.developmentDetails?.stages.analysis || false} onChange={() => handleDevStageChange('analysis')} disabled={!canEditProject || isSubmitting} />
                                      <DevStageCheckbox label="تصميم UI/UX" isChecked={formData.developmentDetails?.stages.design || false} onChange={() => handleDevStageChange('design')} disabled={!canEditProject || isSubmitting} />
                                      <DevStageCheckbox label="برمجة" isChecked={formData.developmentDetails?.stages.programming || false} onChange={() => handleDevStageChange('programming')} disabled={!canEditProject || isSubmitting} />
                                      <DevStageCheckbox label="اختبار" isChecked={formData.developmentDetails?.stages.testing || false} onChange={() => handleDevStageChange('testing')} disabled={!canEditProject || isSubmitting} />
                                      <DevStageCheckbox label="إطلاق" isChecked={formData.developmentDetails?.stages.launch || false} onChange={() => handleDevStageChange('launch')} disabled={!canEditProject || isSubmitting} />
                                  </div>
                              </div>
                          )}

                          {/* Digital Marketing Fields */}
                          {formData.projectType === ProjectType.DIGITAL_MARKETING && (
                              <>
                                  <div className="md:col-span-2"><h3 className="text-base font-semibold text-slate-200 border-b border-[#3E527B] pb-2">تفاصيل التسويق الرقمي</h3></div>
                                  <div className="md:col-span-2">
                                      <label htmlFor="marketingDetails.platforms" className="block text-sm font-medium text-slate-300 mb-1">المنصات</label>
                                      <input type="text" id="marketingDetails.platforms" name="marketingDetails.platforms" value={formData.marketingDetails?.platforms || ''} onChange={handleChange} placeholder="Google, Meta, etc." className="w-full bg-[#2C3E5F] border border-[#3E527B] rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#00B7C1] disabled:bg-[#2C3E5F]/50" />
                                  </div>
                                  <div>
                                      <label htmlFor="marketingDetails.campaignDurationDays" className="block text-sm font-medium text-slate-300 mb-1">مدة الحملة (بالأيام)</label>
                                      <input type="number" id="marketingDetails.campaignDurationDays" name="marketingDetails.campaignDurationDays" value={formData.marketingDetails?.campaignDurationDays || 30} onChange={handleChange} className="w-full bg-[#2C3E5F] border border-[#3E527B] rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#00B7C1] disabled:bg-[#2C3E5F]/50" />
                                  </div>
                                  <div>
                                      <label htmlFor="marketingDetails.monthlyBudget" className="block text-sm font-medium text-slate-300 mb-1">الميزانية الشهرية (SAR)</label>
                                      <input type="number" id="marketingDetails.monthlyBudget" name="marketingDetails.monthlyBudget" value={formData.marketingDetails?.monthlyBudget || 0} onChange={handleChange} className="w-full bg-[#2C3E5F] border border-[#3E527B] rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#00B7C1] disabled:bg-[#2C3E5F]/50" />
                                  </div>
                              </>
                          )}
                      </div>
                  </div>
              </fieldset>
          </form>
        );
      case 'tasks':
        return (
          <>
            <TaskList 
                projectId={project!.id}
                tasksToDisplay={paginatedParentTasks}
                allProjectTasks={tasks}
                users={users}
                currentUser={currentUser}
                onAddTask={addTask}
                onUpdateTask={updateTask}
                canEdit={canEditProject}
            />
            {totalTaskPages > 1 && (
              <div className="mt-4 border-t border-[#2C3E5F]">
                <PaginationControls
                  currentPage={taskCurrentPage}
                  totalPages={totalTaskPages}
                  onPageChange={setTaskCurrentPage}
                  itemsPerPage={taskItemsPerPage}
                  onItemsPerPageChange={(size) => {
                    setTaskItemsPerPage(size);
                    setTaskCurrentPage(1);
                  }}
                  totalItems={parentTasks.length}
                  pageSizeOptions={[5, 10, 20]}
                />
              </div>
            )}
          </>
        );
      case 'timeline':
        return <ProjectTimeline tasks={tasks} users={users} />;
      case 'files':
        return (
          <>
            {canEditProject && (
              <div
                onDragEnter={handleDragEnter}
                onDragLeave={handleDragLeave}
                onDragOver={handleDragOver}
                onDrop={handleDrop}
                className={`border-2 border-dashed border-[#3E527B] rounded-lg p-8 text-center transition-colors ${isDragging ? 'bg-[#2C3E5F]/50 border-[#00B7C1]' : ''}`}
              >
                <input type="file" id="file-upload" multiple onChange={handleFileChange} className="hidden" />
                <label htmlFor="file-upload" className="cursor-pointer flex flex-col items-center justify-center">
                    <UploadIcon className="w-12 h-12 text-slate-400 mb-2" />
                    <p className="text-slate-300 font-semibold">اسحب الملفات إلى هنا أو انقر للاختيار</p>
                    <p className="text-xs text-slate-500 mt-1">يمكنك تحميل مستندات، صور، أو أي ملفات أخرى متعلقة بالمشروع</p>
                </label>
              </div>
            )}
            <div className="mt-6 space-y-3">
              {projectFiles.length > 0 ? (
                  projectFiles.map(file => (
                      <div key={file.name} className="bg-[#2C3E5F]/50 p-3 rounded-lg flex items-center justify-between">
                          <div className="flex items-center gap-3 overflow-hidden">
                              <FileIcon className="w-6 h-6 text-slate-400 flex-shrink-0" />
                              <div className="overflow-hidden">
                                  <p className="text-sm font-medium text-slate-100 truncate">{file.name}</p>
                                  <p className="text-xs text-slate-400">{formatFileSize(file.size)}</p>
                              </div>
                          </div>
                          {canEditProject && (
                              <button onClick={() => handleFileDelete(file.name)} className="text-red-400 hover:text-red-300 p-1 rounded-full transition-colors">
                                  <TrashIcon className="w-5 h-5" />
                              </button>
                          )}
                      </div>
                  ))
              ) : (
                 <p className="text-center text-slate-400 py-8">لا توجد ملفات مرفقة بهذا المشروع بعد.</p>
              )}
            </div>
          </>
        );
      default: return null;
    }
  }

  const customHeader = (
    <div className="p-6 border-b border-[#2C3E5F] bg-gradient-to-b from-[#1A2B4D] to-[#1A2B4D]/50 rounded-t-xl">
      <div className="flex justify-between items-start">
        <h2 className="text-2xl font-bold">{isCreating ? 'إنشاء مشروع جديد' : formData.name}</h2>
        <button 
          onClick={handleClose} 
          className="text-slate-400 hover:text-white transition-colors"
          aria-label="Close"
        >
          <XIcon className="h-6 w-6" />
        </button>
      </div>
      {!isCreating && totalTasks > 0 && (
            <div className="mt-4">
                <div className="flex justify-between items-center mb-1">
                    <span className="text-sm font-medium text-slate-300">تقدم المشروع</span>
                    <span className="text-sm font-bold text-slate-200">{progress}%</span>
                </div>
                <div className="w-full bg-[#2C3E5F] rounded-full h-2">
                    <div 
                        className="bg-[#00B7C1] h-2 rounded-full transition-all duration-300" 
                        style={{ width: `${progress}%` }}
                    ></div>
                </div>
            </div>
        )}
      <div className="mt-4">
            <nav className="-mb-[1px] flex space-x-4 border-b border-[#2C3E5F]" aria-label="Tabs">
                <button
                    onClick={() => setActiveTab('details')}
                    className={`${activeTab === 'details' ? 'border-[#00B7C1] text-[#00B7C1]' : 'border-transparent text-slate-400 hover:text-slate-200 hover:border-slate-500'}
                                whitespace-nowrap py-3 px-1 border-b-2 font-semibold text-sm transition-colors`}
                >
                    تفاصيل
                </button>
                <button
                    onClick={() => setActiveTab('tasks')}
                    disabled={isCreating}
                    className={`${activeTab === 'tasks' ? 'border-[#00B7C1] text-[#00B7C1]' : 'border-transparent text-slate-400 hover:text-slate-200 hover:border-slate-500'}
                                whitespace-nowrap py-3 px-1 border-b-2 font-semibold text-sm transition-colors disabled:opacity-50 disabled:cursor-not-allowed`}
                >
                    المهام ({tasks.length})
                </button>
                <button
                    onClick={() => setActiveTab('timeline')}
                    disabled={isCreating}
                    className={`${activeTab === 'timeline' ? 'border-[#00B7C1] text-[#00B7C1]' : 'border-transparent text-slate-400 hover:text-slate-200 hover:border-slate-500'}
                                whitespace-nowrap py-3 px-1 border-b-2 font-semibold text-sm transition-colors disabled:opacity-50 disabled:cursor-not-allowed`}
                >
                    الجدول الزمني
                </button>
                <button
                    onClick={() => setActiveTab('files')}
                    disabled={isCreating}
                    className={`${activeTab === 'files' ? 'border-[#00B7C1] text-[#00B7C1]' : 'border-transparent text-slate-400 hover:text-slate-200 hover:border-slate-500'}
                                whitespace-nowrap py-3 px-1 border-b-2 font-semibold text-sm transition-colors disabled:opacity-50 disabled:cursor-not-allowed`}
                >
                    الملفات ({projectFiles.length})
                </button>
            </nav>
        </div>
    </div>
  );

  const footer = activeTab === 'details' ? (
    <>
      <button type="button" onClick={handleClose} className="btn btn-secondary" disabled={isSubmitting}>
          {canEditProject ? 'إلغاء' : 'إغلاق'}
      </button>
      {canEditProject && (
          <button type="submit" form="project-form" className="btn btn-primary" disabled={isCreating ? isSubmitting : (!hasUnsavedChanges || isSubmitting)}>
              {isSubmitting ? 'جارٍ الحفظ...' : (isCreating ? 'إنشاء المشروع' : 'حفظ التغييرات')}
          </button>
      )}
    </>
  ) : undefined;

  return (
    <BaseModal 
      isOpen={true} 
      onClose={handleClose} 
      header={customHeader} 
      footer={footer}
      maxWidth="max-w-4xl"
    >
      {renderTabContent()}
    </BaseModal>
  );
};

export default ProjectModal;